name: Rust

on:
  schedule:
  - cron: 0 0 * * SUN

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run
      run: cargo run --bin crates_io_search

    - name: Commit
      uses: EndBug/add-and-commit@v2.1.0
      with:
        author_name: dalance
        author_email: dalance@gmail.com
        message: "Add crates_io_search result"
        path: "./crates_io_search"
        pattern: "results.toml"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
